import {
  SiJavascript,
  SiTypescript,
  SiReact,
  SiNextdotjs,
  SiTailwindcss,
  SiNodedotjs,
  SiGit,
  SiDocker,
  SiVercel,
  SiPython,
  SiPytorch,
  SiR,
  SiTidyverse,
  SiGo,
  SiRust,
  SiGithub,
  SiPostgresql,
  SiMongodb,
  SiPrisma,
  SiDrizzle,
  SiHtml5,
  SiCss3,
  SiEthereum,
  SiSolana,
  SiBitcoin,
  SiAmazon,
  SiLatex,
  SiRabbitmq,
  SiGnubash,
  SiNeovim,
  SiNginx,
  SiNumpy,
  SiPandas,
  SiJupyter,
  SiLinux,
} from "react-icons/si";
import { calculatePosition } from "@/utils/calculation";

interface IconData {
  Icon: React.ElementType;
  position: [number, number, number];
  color: string;
}

export const SKILLS_ICONS: IconData[] = [
  { Icon: SiJavascript, color: "#F7DF1E" },
  { Icon: SiTypescript, color: "#3178C6" },
  { Icon: SiReact, color: "#61DAFB" },
  { Icon: SiNextdotjs, color: "#000000" },
  { Icon: SiTailwindcss, color: "#06B6D4" },
  { Icon: SiNodedotjs, color: "#339933" },
  { Icon: SiGit, color: "#F05032" },
  { Icon: SiDocker, color: "#2496ED" },
  { Icon: SiVercel, color: "#000000" },
  { Icon: SiPython, color: "#3776AB" },
  { Icon: SiPytorch, color: "#EE4C2C" },
  { Icon: SiR, color: "#276DC3" },
  { Icon: SiTidyverse, color: "#4699A5" },
  { Icon: SiGo, color: "#00ADD8" },
  { Icon: SiRust, color: "#000000" },
  { Icon: SiGithub, color: "#181717" },
  { Icon: SiPostgresql, color: "#336791" },
  { Icon: SiMongodb, color: "#47A248" },
  { Icon: SiPrisma, color: "#2D3748" },
  { Icon: SiDrizzle, color: "#1A1919" },
  { Icon: SiHtml5, color: "#E34F26" },
  { Icon: SiCss3, color: "#1572B6" },
  { Icon: SiEthereum, color: "#3C3C3D" },
  { Icon: SiSolana, color: "#8C4FFF" },
  { Icon: SiBitcoin, color: "#FF9900" },
  { Icon: SiAmazon, color: "#FF9900" },
  { Icon: SiLatex, color: "#008080" },
  { Icon: SiRabbitmq, color: "#FF6600" },
  { Icon: SiGnubash, color: "#4EAA25" },
  { Icon: SiNeovim, color: "#57A143" },
  { Icon: SiNginx, color: "#009639" },
  { Icon: SiNumpy, color: "#0076A8" },
  { Icon: SiPandas, color: "#150458" },
  { Icon: SiJupyter, color: "#F37626" },
  { Icon: SiLinux, color: "#000000" },
].map((icon, index, array) => ({
  ...icon,
  position: calculatePosition(index, array.length),
}));
